### ISSUE TITLE
Serializing & materializing a Bag with duplicate elements fails

### ISSUE THREAD

**Issue by Rinzwind** [svenvc/ston#22]
The following variation on `STONWriteReadTests>>#testCollections` signals an error:

```
testCollections2
	| collections |
	collections := STON listClass withAll: {
		Bag withAll: { 1@2. 3@4. 1@2. 3@4. 1@2 } }.
	self serializeAndMaterialize: collections
```
⇒ `STONReaderError: At character 37: 'Inconsistent reference resolution'`

Tested with the version of STON as included in Pharo 7 (“Pharo-7.0.0+rc1.build.117.sha.65868b2ab36e77ebb1db5f750725205e92999116 (64 Bit)”).

**Comment by Rinzwind** [comment]
Thanks! That seems to work. Two observations though:

* This makes the notation for Bag more implementation-dependent (the GemStone implementation of Bag has different instance variables than the Pharo one)
* Bags serialized by the previous version of STON can not be materialized by this version anymore (`STON fromString: 'Bag[''abc'']'` no longer works)

An alternative solution I had in mind is to postpone adding the elements to the Bag to happen after the reference resolution. When creating the Bag, put its elements in an OrderedCollection that serves as a “placeholder”:

```
Bag class>>fromSton: stonReader

	| elementsPlaceholder collection |
	elementsPlaceholder := OrderedCollection new.
	collection := self with: elementsPlaceholder.
	stonReader parseListDo: [ :each |
		elementsPlaceholder add: each ].
	^ collection
```

Then in `#stonProcessSubObjects:`, add the elements to the Bag after resolving their references:

```
Bag>>stonProcessSubObjects: block

	| contentsPlaceholder |
	contentsPlaceholder := self anyOne.
	self removeAll.
	contentsPlaceholder do: [ :element |
		self add: (block value: element) ].
```

This also makes the `#testCollections2` given above pass. As a sanity-check, it's also able to read a self-referencing Bag (`b := STON fromString: 'Bag[@1]'. b anyOne == b` ⇒ `true`) (this wouldn't be the case, I think, if the reference-resolution were done in `#fromSton:`, which is what I initially had in mind). What does not work yet is reading a Bag without any references, because in that case `#stonProcessSubObjects:` is simply not sent; I'm not sure yet how best to handle that.

**Comment by svenvc** [comment]
By design and by nature, a serialisation format like STON exposes the internal structure of objects. It is just for a limited number of classes that a reasonably abstract and more implementation independent representation can be chosen.

For this reason, I do not consider cross-platform or inter-version compatibility as real goals. But of course I will try to maintain it.

With that being said, I am considering using another custom representation of Bags, with the value->occurences dictionary directly exposed, like
```
Bag { #a->1. #b->2 }
```
Would that work on Gemstone ? 

BTW, I consider the old representation
```
 Bag [ #a, #a, #b, #b, #b ]
```
as almost a bug, since it explodes the Bag's size.

**Comment by Rinzwind** [comment]
Ok, thanks! I think we can consider this issue as closed.
